Repository BA-BA-Project/baba-back, pull requests merged in 2023-05, with the labels that each got.

#136 feat: 그룹 정보 변경 API를 구현한다.
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/domain/Like.java
  back/src/main/java/com/baba/back/content/dto/ContentUpdateTitleAndCardStyleRequest.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/domain/member/Color.java
  back/src/main/java/com/baba/back/oauth/dto/UpdateGroupRequest.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/main/resources/application.yml
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/BabyTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#139 refactor: 그룹 멤버 정보 변경 API에서 query parameter를 삭제한다.
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ♻️ 리팩토링

#142 feat: 성장 앨범 모두 조회 API 구현
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/repository/ContentRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
Labels: ✨ 기능

#141 feat: 그룹 멤버 삭제 API를 구현한다.
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#144 feat: 그룹 삭제 API를 구현한다.
  back/src/main/java/com/baba/back/baby/domain/invitation/Invitation.java
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#149 feat: 성장 앨범 한개 조회 API 구현
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/repository/LikeRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/repository/LikeRepositoryTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
Labels: 🐛 버그, ✨ 기능

#153 refactor: isMybaby 필드 추가
  back/src/main/java/com/baba/back/baby/dto/BabiesResponse.java
  back/src/main/java/com/baba/back/baby/dto/IsMyBabyResponse.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
Labels: ♻️ 리팩토링
