Repository BA-BA-Project/baba-back, pull requests merged in 2023-03, with the labels that each got.

#62 사용자 정보 조회 API 를 구현한다
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/domain/member/Icon.java
  back/src/main/java/com/baba/back/oauth/domain/member/IconColor.java
  back/src/main/java/com/baba/back/oauth/domain/member/Introduction.java
  back/src/main/java/com/baba/back/oauth/domain/member/Member.java
  back/src/main/java/com/baba/back/oauth/domain/member/Name.java
  back/src/main/java/com/baba/back/oauth/dto/LoginTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MemberResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SignTokenResponse.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/oauth/service/SignTokenProvider.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#63 Clock Bean 등록
  back/src/main/java/com/baba/back/common/config/TimeConfig.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ♻️ 리팩토링

#64 토큰 재발급 API를 구현한다.
  back/src/main/java/com/baba/back/oauth/config/LoginConfig.java
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/domain/token/Token.java
  back/src/main/java/com/baba/back/oauth/dto/TokenRefreshRequest.java
  back/src/main/java/com/baba/back/oauth/dto/TokenRefreshResponse.java
  back/src/main/java/com/baba/back/oauth/exception/TokenNotFoundException.java
  back/src/main/java/com/baba/back/oauth/repository/TokenRepository.java
  back/src/main/java/com/baba/back/oauth/service/AccessTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/main/java/com/baba/back/oauth/service/RefreshTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/SignTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/TokenProvider.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/token/TokenTest.java
  back/src/test/java/com/baba/back/oauth/repository/TokenRepositoryTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/RefreshTokenProviderTest.java
  back/src/test/java/com/baba/back/oauth/service/TokenProviderTest.java
Labels: ✨ 기능

#67 AcceptanceTest의 요청을 메소드로 만든다.
  back/src/main/java/com/baba/back/oauth/domain/token/Token.java
  back/src/main/java/com/baba/back/oauth/repository/TokenRepository.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/token/TokenTest.java
  back/src/test/java/com/baba/back/oauth/repository/TokenRepositoryTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/RefreshTokenProviderTest.java
Labels: ♻️ 리팩토링

#70 그룹을 커스터마이징할 수 있게 변경한다.
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/main/java/com/baba/back/relation/repository/RelationGroupRepository.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/RefreshTokenProviderTest.java
  back/src/test/java/com/baba/back/relation/domain/RelationGroupTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
  back/src/test/resources/truncate.sql
Labels: ♻️ 리팩토링

#72 Swagger UI https 설정을 한다.
  back/src/main/resources/application.yml
Labels: 🐛 버그

#74 그룹 추가 시, 그룹 색상을 추가할 수 있도록 변경한다.
  back/src/main/java/com/baba/back/oauth/domain/member/Color.java
  back/src/main/java/com/baba/back/oauth/domain/member/Icon.java
  back/src/main/java/com/baba/back/oauth/domain/member/Member.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/member/ColorTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: 🐛 버그

#77 소셜 로그인 API를 변경한다.
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/dto/LoginTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SignTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SocialLoginResponse.java
  back/src/main/java/com/baba/back/oauth/dto/TokenResponse.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
Labels: ♻️ 리팩토링

#75 등록된 아기 리스트를 조회한다.
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/domain/Baby.java
  back/src/main/java/com/baba/back/baby/dto/BabiesResponse.java
  back/src/main/java/com/baba/back/baby/dto/BabyResponse.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/domain/member/Color.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/main/java/com/baba/back/relation/domain/Relations.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/RelationsTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/relation/domain/RelationGroupTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
Labels: ✨ 기능

#79 약관 제공 API를 구현한다.
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/domain/Terms.java
  back/src/main/java/com/baba/back/oauth/dto/SearchTermsResponse.java
  back/src/main/java/com/baba/back/oauth/dto/TermsResponse.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
Labels: ✨ 기능

#81 성장 앨범 추가 API를 수정한다
  back/src/main/java/com/baba/back/baby/domain/Babies.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/dto/CreateContentResponse.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/dto/SignUpWithBabyResponse.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/BabiesTest.java
  back/src/test/java/com/baba/back/baby/domain/RelationsTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/token/TokenTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
Labels: ♻️ 리팩토링

#84 chore: API url 변경
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/SimpleRestAssured.java
Labels: ♻️ 리팩토링

#83 성장 앨범 메인 조회 API 를 구현한다.
  back/src/main/java/com/baba/back/baby/domain/Baby.java
  back/src/main/java/com/baba/back/common/domain/Name.java
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/domain/content/Content.java
  back/src/main/java/com/baba/back/content/domain/content/ContentDate.java
  back/src/main/java/com/baba/back/content/domain/content/ImageSource.java
  back/src/main/java/com/baba/back/content/domain/content/Title.java
  back/src/main/java/com/baba/back/content/dto/ContentResponse.java
  back/src/main/java/com/baba/back/content/dto/ContentsResponse.java
  back/src/main/java/com/baba/back/content/repository/ContentRepository.java
  back/src/main/java/com/baba/back/content/repository/LikeRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/domain/member/Member.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/common/domain/NameTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/domain/LikeTest.java
  back/src/test/java/com/baba/back/content/domain/content/ContentTest.java
  back/src/test/java/com/baba/back/content/repository/ContentRepositoryTest.java
  back/src/test/java/com/baba/back/content/repository/LikeRepositoryTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
Labels: ✨ 기능

#86 chore: API HTTP Method 변경
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/SimpleRestAssured.java
Labels: ♻️ 리팩토링

#85 feat: 약관 동의 API를 구현한다.
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/domain/Terms.java
  back/src/main/java/com/baba/back/oauth/dto/AgreeTermsRequest.java
  back/src/main/java/com/baba/back/oauth/dto/TermsRequest.java
  back/src/main/java/com/baba/back/oauth/exception/TermsBadRequestException.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/main/resources/logback-spring.xml
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/TermsTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
Labels: ✨ 기능

#87 feat: 초대 코드 생성 API를 구현한다.
  back/build.gradle
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Code.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Expiration.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Invitation.java
  back/src/main/java/com/baba/back/baby/domain/invitation/InvitationCode.java
  back/src/main/java/com/baba/back/baby/dto/CreateInviteCodeRequest.java
  back/src/main/java/com/baba/back/baby/dto/CreateInviteCodeResponse.java
  back/src/main/java/com/baba/back/baby/exception/ExpirationBadReqeustException.java
  back/src/main/java/com/baba/back/baby/exception/InviteCodeBadRequestException.java
  back/src/main/java/com/baba/back/baby/exception/RelationGroupNotFoundException.java
  back/src/main/java/com/baba/back/baby/repository/InvitationCodeRepository.java
  back/src/main/java/com/baba/back/baby/repository/InvitationRepository.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/baby/service/CodeGenerator.java
  back/src/main/java/com/baba/back/baby/service/RandomCodeGenerator.java
  back/src/main/java/com/baba/back/relation/repository/RelationGroupRepository.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/CodeTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/ExpirationTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/relation/repository/RelationGroupRepositoryTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
Labels: ✨ 기능

#90 feat: 초대 코드 정보 확인 API를 구현한다.
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Code.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Expiration.java
  back/src/main/java/com/baba/back/baby/domain/invitation/InvitationCode.java
  back/src/main/java/com/baba/back/baby/dto/InviteCodeBabyResponse.java
  back/src/main/java/com/baba/back/baby/dto/SearchInviteCodeResponse.java
  back/src/main/java/com/baba/back/baby/exception/InvitationCodeBadRequestException.java
  back/src/main/java/com/baba/back/baby/exception/InvitationCodeNotFoundException.java
  back/src/main/java/com/baba/back/baby/exception/InvitationNotFoundException.java
  back/src/main/java/com/baba/back/baby/repository/InvitationCodeRepository.java
  back/src/main/java/com/baba/back/baby/repository/InvitationRepository.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/config/LoginConfig.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/CodeTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/ExpirationTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/InvitationCodeTest.java
  back/src/test/java/com/baba/back/baby/repository/InvitationCodeRepositoryTest.java
  back/src/test/java/com/baba/back/baby/repository/InvitationRepositoryTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
Labels: ✨ 기능

#89 댓글 추가 기능을 구현한다.
  back/src/main/java/com/baba/back/baby/domain/Baby.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Expiration.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Invitation.java
  back/src/main/java/com/baba/back/baby/domain/invitation/InvitationCode.java
  back/src/main/java/com/baba/back/baby/service/RandomCodeGenerator.java
  back/src/main/java/com/baba/back/common/FileHandler.java
  back/src/main/java/com/baba/back/common/FileHandlerS3.java
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/domain/comment/Comment.java
  back/src/main/java/com/baba/back/content/domain/comment/Tag.java
  back/src/main/java/com/baba/back/content/domain/comment/Text.java
  back/src/main/java/com/baba/back/content/domain/content/Content.java
  back/src/main/java/com/baba/back/content/domain/content/ImageFile.java
  back/src/main/java/com/baba/back/content/dto/CreateCommentRequest.java
  back/src/main/java/com/baba/back/content/exception/TagBadRequestException.java
  back/src/main/java/com/baba/back/content/exception/TextLenthBadRequestException.java
  back/src/main/java/com/baba/back/content/repository/CommentRepository.java
  back/src/main/java/com/baba/back/content/repository/TagRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/domain/member/Member.java
  back/src/main/java/com/baba/back/oauth/domain/token/Token.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/RelationsTest.java
  back/src/test/java/com/baba/back/baby/repository/InvitationCodeRepositoryTest.java
  back/src/test/java/com/baba/back/baby/repository/InvitationRepositoryTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/common/FileHandlerS3Test.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/domain/ImageFileTest.java
  back/src/test/java/com/baba/back/content/domain/LikeTest.java
  back/src/test/java/com/baba/back/content/domain/comment/TextTest.java
  back/src/test/java/com/baba/back/content/repository/ContentRepositoryTest.java
  back/src/test/java/com/baba/back/content/repository/LikeRepositoryTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
  back/src/test/java/com/baba/back/relation/domain/RelationGroupTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
Labels: ✨ 기능

#93 feat: 초대받은 회원가입 API를 구현한다.
  back/src/main/java/com/baba/back/baby/domain/invitation/Invitation.java
  back/src/main/java/com/baba/back/baby/domain/invitation/InvitationCode.java
  back/src/main/java/com/baba/back/baby/domain/invitation/Invitations.java
  back/src/main/java/com/baba/back/baby/exception/InvitationNotFoundException.java
  back/src/main/java/com/baba/back/baby/exception/InvitationsBadRequestException.java
  back/src/main/java/com/baba/back/baby/repository/InvitationCodeRepository.java
  back/src/main/java/com/baba/back/baby/repository/InvitationRepository.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/config/LoginConfig.java
  back/src/main/java/com/baba/back/oauth/config/SignUpConfig.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/dto/SignUpWithCodeRequest.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/resources/application.yml
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/CodeTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/InvitationCodeTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/InvitationTest.java
  back/src/test/java/com/baba/back/baby/domain/invitation/InvitationsTest.java
  back/src/test/java/com/baba/back/baby/repository/InvitationCodeRepositoryTest.java
  back/src/test/java/com/baba/back/baby/repository/InvitationRepositoryTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#95 feat: 마이 그룹별 조회 API를 구현한다.
  back/src/main/java/com/baba/back/baby/domain/Babies.java
  back/src/main/java/com/baba/back/content/domain/content/Content.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/dto/MyGroupMemberResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MyGroupResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MyProfileResponse.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/repository/RelationGroupRepository.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/content/domain/content/ContentTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/relation/domain/RelationTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationGroupRepositoryTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
Labels: ✨ 기능

#99 멤버 조회 API 수정
  back/src/main/java/com/baba/back/oauth/dto/MemberResponse.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ♻️ 리팩토링

#96 성장앨범 댓글보기 API 를 구현한다.
  back/build.gradle
  back/src/main/java/com/baba/back/baby/domain/invitation/Code.java
  back/src/main/java/com/baba/back/common/domain/BaseEntity.java
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/domain/comment/Comment.java
  back/src/main/java/com/baba/back/content/dto/CommentResponse.java
  back/src/main/java/com/baba/back/content/dto/CommentsResponse.java
  back/src/main/java/com/baba/back/content/repository/CommentRepository.java
  back/src/main/java/com/baba/back/content/repository/LikeRepository.java
  back/src/main/java/com/baba/back/content/repository/TagRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/dto/SignUpWithCodeRequest.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/domain/comment/CommentTest.java
  back/src/test/java/com/baba/back/content/repository/CommentRepositoryTest.java
  back/src/test/java/com/baba/back/content/repository/LikeRepositoryTest.java
  back/src/test/java/com/baba/back/content/repository/TagRepositoryTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#101 feat: 그룹 추가 API를 구현한다.
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/dto/CreateGroupRequest.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/main/java/com/baba/back/relation/exception/RelationGroupBadRequestException.java
  back/src/main/java/com/baba/back/relation/repository/RelationGroupRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/relation/domain/RelationGroupTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationGroupRepositoryTest.java
  back/src/test/resources/truncate.sql
Labels: ✨ 기능
