Repository BA-BA-Project/baba-back, pull requests merged in 2023-04, with the labels that each got.

#104 feat: 다른 아기 프로필 조회 API를 구현한다.
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/dto/BabyProfileResponse.java
  back/src/main/java/com/baba/back/oauth/dto/FamilyGroupResponse.java
  back/src/main/java/com/baba/back/oauth/dto/GroupMemberResponse.java
  back/src/main/java/com/baba/back/oauth/dto/GroupResponse.java
  back/src/main/java/com/baba/back/oauth/dto/GroupResponseWithFamily.java
  back/src/main/java/com/baba/back/oauth/dto/MyGroupMemberResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MyGroupResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MyProfileResponse.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/repository/RelationGroupRepository.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ✨ 기능

#108 fix: 테스트 수정에 따른 오류 해결
  back/src/test/java/com/baba/back/AcceptanceTest.java
Labels: 🐛 버그

#107 성장 앨범 좋아요 자세히 보기 API를 구현한다
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/dto/IconResponse.java
  back/src/main/java/com/baba/back/content/dto/LikesResponse.java
  back/src/main/java/com/baba/back/content/repository/LikeRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
Labels: ✨ 기능

#110 아이콘 색상 응답 시 RGB 형태로 응답하도록 변경
  back/src/main/java/com/baba/back/oauth/domain/member/Color.java
  back/src/main/java/com/baba/back/oauth/domain/member/Icon.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/member/ColorTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: 🐛 버그, ♻️ 리팩토링

#113 like entity만 soft delete를 수행하도록 변경
  back/src/main/java/com/baba/back/common/domain/BaseEntity.java
  back/src/main/java/com/baba/back/content/domain/Like.java
Labels: ♻️ 리팩토링

#120 feat: 아기 이름 변경 API를 구현한다.
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/domain/Baby.java
  back/src/main/java/com/baba/back/baby/dto/BabyNameRequest.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/exception/MemberAuthorizationException.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/SimpleRestAssured.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/BabyTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
Labels: ✨ 기능

#119 성장 앨범 생성 시 응답 메시지를 추가한다
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
Labels: ♻️ 리팩토링

#128 feat: 초대 코드로 아기 추가 API를 구현한다.
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/dto/InviteCodeRequest.java
  back/src/main/java/com/baba/back/baby/exception/RelationBadRequestException.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
Labels: ✨ 기능

#133 fix: 가족 관계는 초대코드로 아기를 추가할 수 없게 한다.
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
Labels: 🐛 버그

#130 성장 앨범 수정 API를 구현한다
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/dto/ContentUpdateTitleAndCardStyleRequest.java
  back/src/main/java/com/baba/back/content/dto/UpdateContentPhotoRequest.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/SimpleRestAssured.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
Labels: ✨ 기능
