Repository BA-BA-Project/baba-back, pull requests merged in 2023-02, with the labels that each got.

#17 스웨거를 통해 API를 문서화한다.
  back/build.gradle
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/config/LoginConfig.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/support/Login.java
  back/src/main/java/com/baba/back/swagger/BadRequestResponse.java
  back/src/main/java/com/baba/back/swagger/CreatedResponse.java
  back/src/main/java/com/baba/back/swagger/ForbiddenResponse.java
  back/src/main/java/com/baba/back/swagger/IntervalServerErrorResponse.java
  back/src/main/java/com/baba/back/swagger/NotFoundResponse.java
  back/src/main/java/com/baba/back/swagger/OkResponse.java
  back/src/main/java/com/baba/back/swagger/OpenApiConfig.java
  back/src/main/java/com/baba/back/swagger/UnAuthorizedResponse.java
  back/src/main/resources/application.yml
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
Labels: ✨ 기능

#16 Service 테스트를 Mock 테스트로 변경한다.
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/exception/MemberNotFoundException.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/FakeOAuthClient.java
  back/src/test/java/com/baba/back/oauth/TestConfig.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
Labels: ♻️ 리팩토링

#19 feat: 컨텐츠 생성 API를 구현한다.
  back/build.gradle
  back/src/main/java/com/baba/back/baby/domain/Baby.java
  back/src/main/java/com/baba/back/baby/exception/BabyNotFoundException.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/common/ControllerAdvice.java
  back/src/main/java/com/baba/back/common/FileHandlerS3.java
  back/src/main/java/com/baba/back/common/config/AwsConfig.java
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/domain/FileHandler.java
  back/src/main/java/com/baba/back/content/domain/ImageFile.java
  back/src/main/java/com/baba/back/content/domain/content/CardStyle.java
  back/src/main/java/com/baba/back/content/domain/content/Content.java
  back/src/main/java/com/baba/back/content/domain/content/ContentDate.java
  back/src/main/java/com/baba/back/content/domain/content/ImageSource.java
  back/src/main/java/com/baba/back/content/domain/content/Title.java
  back/src/main/java/com/baba/back/content/dto/CreateContentRequest.java
  back/src/main/java/com/baba/back/content/dto/CreateContentResponse.java
  back/src/main/java/com/baba/back/content/exception/CardStyleBadRequestException.java
  back/src/main/java/com/baba/back/content/exception/ContentAuthorizationException.java
  back/src/main/java/com/baba/back/content/exception/ContentDateBadRequestException.java
  back/src/main/java/com/baba/back/content/exception/FileHandlerServerException.java
  back/src/main/java/com/baba/back/content/exception/ImageFileBadRequestException.java
  back/src/main/java/com/baba/back/content/exception/ImageSourceBadRequestException.java
  back/src/main/java/com/baba/back/content/exception/TitleLengthBadRequestException.java
  back/src/main/java/com/baba/back/content/repository/ContentRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/exception/AuthorizationException.java
  back/src/main/java/com/baba/back/exception/ServerException.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/main/resources/application.yml
  back/src/test/java/com/baba/back/common/FileHandlerS3Test.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/domain/ImageFileTest.java
  back/src/test/java/com/baba/back/content/domain/ImageSourceTest.java
  back/src/test/java/com/baba/back/content/domain/content/CardStyleTest.java
  back/src/test/java/com/baba/back/content/domain/content/ContentDateTest.java
  back/src/test/java/com/baba/back/content/domain/content/ContentTest.java
  back/src/test/java/com/baba/back/content/domain/content/TitleTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/relation/domain/RelationGroupTest.java
Labels: ✨ 기능

#23 ci: dev로 pull request시 ci가 동작하도록 설정한다.
  .github/workflows/ci.yml
Labels: ✨ 기능

#28 ci: jdk distribution 추가
  .github/workflows/ci.yml
Labels: 🐛 버그

#32 성장 앨범 추가 API를 수정한다.
  back/src/main/java/com/baba/back/common/domain/BaseEntity.java
  back/src/main/java/com/baba/back/content/domain/content/Content.java
  back/src/main/java/com/baba/back/content/exception/ContentBadRequestException.java
  back/src/main/java/com/baba/back/content/repository/ContentRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/test/java/com/baba/back/common/domain/BaseEntityTest.java
  back/src/test/java/com/baba/back/content/domain/LikeTest.java
  back/src/test/java/com/baba/back/content/repository/ContentRepositoryTest.java
  back/src/test/java/com/baba/back/content/repository/LikeRepositoryTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
Labels: ♻️ 리팩토링

#35 소셜 로그인 API를 수정한다.
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  back/src/main/java/com/baba/back/content/controller/ContentController.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/KakaoClient.java
  back/src/main/java/com/baba/back/oauth/OAuthClient.java
  back/src/main/java/com/baba/back/oauth/controller/LoginArgumentResolver.java
  back/src/main/java/com/baba/back/oauth/controller/LoginInterceptor.java
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/dto/MemberTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/OAuthAccessTokenRequest.java
  back/src/main/java/com/baba/back/oauth/dto/SignTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SocialLoginResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SocialTokenRequest.java
  back/src/main/java/com/baba/back/oauth/dto/TokenResponse.java
  back/src/main/java/com/baba/back/oauth/service/JwtTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/MemberTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/main/java/com/baba/back/oauth/service/SignTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/TokenProvider.java
  back/src/main/resources/application.yml
  back/src/main/resources/logback-spring.xml
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/TokenProviderTest.java
  back/src/test/resources/truncate.sql
Labels: ♻️ 리팩토링

#39 배포/개발 서버 cd를 구축한다.
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prd.yml
  back/deploy.sh
  back/src/main/resources/application.yml
  back/src/main/resources/logback-spring.xml
Labels: 🏭인프라

#40 fix: logback 로그 위치 수정
  back/src/main/resources/logback-spring.xml
Labels: ♻️ 리팩토링

#41 배포 환경에서 swagger-ui 막기
  back/src/main/resources/application.yml
Labels: ♻️ 리팩토링

#43 회원가입 API를 변경한다.
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/domain/ColorPicker.java
  back/src/main/java/com/baba/back/oauth/domain/Picker.java
  back/src/main/java/com/baba/back/oauth/domain/RandomColorPicker.java
  back/src/main/java/com/baba/back/oauth/domain/RandomPicker.java
  back/src/main/java/com/baba/back/oauth/domain/member/Icon.java
  back/src/main/java/com/baba/back/oauth/domain/member/IconColor.java
  back/src/main/java/com/baba/back/oauth/domain/member/IconName.java
  back/src/main/java/com/baba/back/oauth/domain/member/Member.java
  back/src/main/java/com/baba/back/oauth/dto/MemberJoinResponse.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/member/IconColorTest.java
  back/src/test/java/com/baba/back/oauth/domain/member/IconNameTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ♻️ 리팩토링

#45 feat: refresh 토큰을 추가한다.
  .github/workflows/ci.yml
  back/src/main/java/com/baba/back/oauth/controller/LoginArgumentResolver.java
  back/src/main/java/com/baba/back/oauth/controller/LoginInterceptor.java
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/domain/token/Token.java
  back/src/main/java/com/baba/back/oauth/dto/MemberTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SignTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/TokenResponse.java
  back/src/main/java/com/baba/back/oauth/exception/TokenBadRequestException.java
  back/src/main/java/com/baba/back/oauth/repository/TokenRepository.java
  back/src/main/java/com/baba/back/oauth/service/AccessTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/MemberTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/main/java/com/baba/back/oauth/service/RefreshTokenProvider.java
  back/src/main/java/com/baba/back/oauth/service/SignTokenProvider.java
  back/src/main/resources/application.yml
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/token/TokenTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
  back/src/test/java/com/baba/back/oauth/service/TokenProviderTest.java
  back/src/test/resources/truncate.sql
Labels: ✨ 기능

#47 SImpleRestAssured를 적용한다.
  back/build.gradle
  back/src/main/java/com/baba/back/baby/dto/SearchDefaultBabyResponse.java
  back/src/main/java/com/baba/back/common/dto/ExceptionResponse.java
  back/src/main/java/com/baba/back/content/dto/CreateContentResponse.java
  back/src/main/java/com/baba/back/content/dto/LikeContentResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MemberJoinResponse.java
  back/src/test/java/com/baba/back/SimpleRestAssured.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/service/ContentServiceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/domain/token/TokenTest.java
Labels: ♻️ 리팩토링

#49 fix: `LoginConfig` 인터셉터 설정 변경
  back/src/main/java/com/baba/back/oauth/config/LoginConfig.java
Labels: 🐛 버그

#52 cd yml 파일의 환경변수를 수정한다.
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prd.yml
Labels: 🐛 버그

#53 jacoco test coverage를 1.0으로 수정한다.
  back/build.gradle
  back/lombok.config
  back/src/main/java/com/baba/back/content/domain/content/CardStyle.java
  back/src/main/java/com/baba/back/content/domain/content/Content.java
  back/src/test/java/com/baba/back/content/acceptance/ContentAcceptanceTest.java
  back/src/test/java/com/baba/back/content/domain/LikeTest.java
  back/src/test/java/com/baba/back/content/domain/content/CardStyleTest.java
  back/src/test/java/com/baba/back/content/domain/content/ContentDateTest.java
  back/src/test/java/com/baba/back/content/domain/content/ContentTest.java
  back/src/test/java/com/baba/back/content/repository/LikeRepositoryTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
Labels: ♻️ 리팩토링

#59 소셜 로그인 API를 수정한다.
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prd.yml
  .github/workflows/ci.yml
  back/src/main/java/com/baba/back/oauth/dto/LoginTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/SignTokenResponse.java
  back/src/main/java/com/baba/back/oauth/dto/TokenResponse.java
  back/src/main/java/com/baba/back/oauth/service/OAuthService.java
  back/src/main/java/com/baba/back/oauth/service/SignTokenProvider.java
  back/src/main/resources/application.yml
  back/src/test/java/com/baba/back/oauth/acceptance/OAuthAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
Labels: ♻️ 리팩토링

#60 회원가입 API를 수정한다.
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/domain/Babies.java
  back/src/main/java/com/baba/back/baby/dto/BabyRequest.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/config/LoginConfig.java
  back/src/main/java/com/baba/back/oauth/config/SignUpConfig.java
  back/src/main/java/com/baba/back/oauth/controller/MemberController.java
  back/src/main/java/com/baba/back/oauth/controller/SignUpArgumentResolver.java
  back/src/main/java/com/baba/back/oauth/controller/SignUpInterceptor.java
  back/src/main/java/com/baba/back/oauth/domain/JoinedMember.java
  back/src/main/java/com/baba/back/oauth/dto/MemberJoinResponse.java
  back/src/main/java/com/baba/back/oauth/dto/MemberSignUpRequest.java
  back/src/main/java/com/baba/back/oauth/dto/MemberSignUpResponse.java
  back/src/main/java/com/baba/back/oauth/exception/JoinedMemberBadRequestException.java
  back/src/main/java/com/baba/back/oauth/exception/JoinedMemberNotFoundException.java
  back/src/main/java/com/baba/back/oauth/exception/MemberBadRequestException.java
  back/src/main/java/com/baba/back/oauth/repository/JoinedMemberRepository.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/oauth/support/SignUp.java
  back/src/main/java/com/baba/back/relation/domain/Relation.java
  back/src/main/java/com/baba/back/relation/repository/RelationRepository.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/domain/BabiesTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/DomainFixture.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
  back/src/test/java/com/baba/back/relation/repository/RelationRepositoryTest.java
  back/src/test/resources/truncate.sql
Labels: ♻️ 리팩토링

#56 sonarlint를 도입한다.
  back/src/main/java/com/baba/back/common/ControllerAdvice.java
  back/src/main/java/com/baba/back/oauth/controller/OAuthController.java
  back/src/main/java/com/baba/back/oauth/domain/RandomPicker.java
  back/src/main/java/com/baba/back/oauth/domain/member/Introduction.java
  back/src/main/java/com/baba/back/oauth/domain/member/Name.java
  back/src/main/java/com/baba/back/oauth/service/TokenProvider.java
  back/src/main/java/com/baba/back/oauth/support/AuthorizationExtractor.java
  back/src/test/java/com/baba/back/baby/domain/BabiesTest.java
  back/src/test/java/com/baba/back/common/FileHandlerS3Test.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/OAuthServiceTest.java
Labels: ♻️ 리팩토링
