Repository BA-BA-Project/baba-back, pull requests merged in 2023-06, with the labels that each got.

#154 refactor: 관계 그룹 로직 수정
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/baby/dto/IsMyBabyResponse.java
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/AcceptanceTest.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/baby/service/BabyServiceTest.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: 🐛 버그, ♻️ 리팩토링

#156 refactor: 아기 삭제응답 코드 수정
  back/.DS_Store
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
Labels: ♻️ 리팩토링

#158 fix: 다른 아기 프로필 조회 API를 수정한다.
  back/src/main/java/com/baba/back/baby/controller/BabyController.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: 🐛 버그

#161 fix: 아기 추가 API를 수정한다.
  back/src/main/java/com/baba/back/baby/service/BabyService.java
  back/src/test/java/com/baba/back/baby/acceptance/BabyAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
Labels: 🐛 버그, ♻️ 리팩토링

#163 refactor: 그룹 컬러를 반환하도록 변경한다.
  back/src/main/java/com/baba/back/content/repository/LikeRepository.java
  back/src/main/java/com/baba/back/content/service/ContentService.java
  back/src/main/java/com/baba/back/oauth/dto/CreateGroupRequest.java
  back/src/main/java/com/baba/back/oauth/dto/UpdateGroupRequest.java
  back/src/main/java/com/baba/back/oauth/service/MemberService.java
  back/src/main/java/com/baba/back/relation/domain/RelationGroup.java
  back/src/test/java/com/baba/back/fixture/RequestFixture.java
  back/src/test/java/com/baba/back/oauth/acceptance/MemberAcceptanceTest.java
  back/src/test/java/com/baba/back/oauth/service/MemberServiceTest.java
Labels: ♻️ 리팩토링
